spring.application.name=modern_library


spring.datasource.url=jdbc:postgresql://localhost:5432/library
spring.datasource.username=postgre
spring.datasource.password=1822
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true